services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "5173:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - app-network
  #   depends_on:
  #     - client
  #     - server
  #   restart: always
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #     # dockerfile: Dockerfile.dev
  client:
    build: 
      context: ./client
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - "80:5173"
    networks:
      - app-network
    depends_on:
      - server
  server:
    build: 
      context: ./server
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge